// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCphYzXm-1OuD-OEBeQcoPfCxLosXV5aTs',
    appId: '1:425679145687:web:6b0b3bcdb7510e52fd7e92',
    messagingSenderId: '425679145687',
    projectId: 'iamapp-80ab7',
    authDomain: 'iamapp-80ab7.firebaseapp.com',
    databaseURL: 'https://iamapp-80ab7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iamapp-80ab7.appspot.com',
    measurementId: 'G-69BBFYNLRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlH6SruyLVmwQQ86MnuwQPXmKd5vzW5JQ',
    appId: '1:425679145687:android:58a963fb4761412efd7e92',
    messagingSenderId: '425679145687',
    projectId: 'iamapp-80ab7',
    databaseURL: 'https://iamapp-80ab7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iamapp-80ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKyEJGhlFViaGZjMSU1gliZoadqxSvoKs',
    appId: '1:425679145687:ios:1e835a1e07d583fafd7e92',
    messagingSenderId: '425679145687',
    projectId: 'iamapp-80ab7',
    databaseURL: 'https://iamapp-80ab7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iamapp-80ab7.appspot.com',
    androidClientId: '425679145687-5l7qf8jbcto9m7s35at5lh5d2drgnijb.apps.googleusercontent.com',
    iosClientId: '425679145687-56680rt1tjn3cfn8rcur055ofpl5ctc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.iam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKyEJGhlFViaGZjMSU1gliZoadqxSvoKs',
    appId: '1:425679145687:ios:c459ac90a8953e89fd7e92',
    messagingSenderId: '425679145687',
    projectId: 'iamapp-80ab7',
    databaseURL: 'https://iamapp-80ab7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iamapp-80ab7.appspot.com',
    androidClientId: '425679145687-5l7qf8jbcto9m7s35at5lh5d2drgnijb.apps.googleusercontent.com',
    iosClientId: '425679145687-6fi74fe62a0ac9htq84nue2sdgnomlb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.iam.RunnerTests',
  );
}
